### ISSUE TITLE
Not suported with EF7: ExecuteDeleteAsync and ExecuteUpdateAsync

### ISSUE THREAD

**Issue by SerhiyBalan** [romantitov/MockQueryable#66]
Hello!

I've been using MockQueryable with .NET6 a lot
Recently my project migrated to .NET 7 (EF Core 7)
And I started to use new EF7 features:

+ ExecuteDeleteAsync

```
            ...
            .Where(user => user.Id == id)
            .ExecuteDeleteAsync();
```

ExecuteDeleteAsync implementation is here
https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs#L316

+ ExecuteUpdateAsync

```
            .Where(user => user.Id == id)
            .ExecuteUpdateAsync(updater => updater
                .SetProperty(
                    user => user.Status,
                    user => status)
                .SetProperty(
                    user => user.ModifiedBy,
                    user => _userContextProvider.GetUserId())
                .SetProperty(
                    user => user.ModifiedOn,
                    user => DateTimeOffset.UtcNow));
```

ExecuteUpdateAsync implementation is here
https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs#L372

I use MockQueryable using a standard pattern:
``` 
           var mock = users.BuildMock();
           _userRepository.Setup(x => x.GetQueryable()).Returns(mock);
```

ToListAsync(), FirstOrDefaultAsync() and others works perfectly with this pattern.

Unfortunately ExecuteUpdateAsync  / ExecuteDeleteAsync doesn't work at all :( 

When I try to run a unit test, a mocked `GetQueryable` method works nicely as usual, but it throws an exception on ExecuteDeleteAsync

```
 <System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: There is no method 'ExecuteDelete' on type 'Microsoft.EntityFrameworkCore.RelationalQueryableExtensions' that matches the specified arguments
   at System.Linq.EnumerableRewriter.FindMethod(Type type, String name, ReadOnlyCollection`1 args, Type[] typeArgs)
   at System.Linq.EnumerableRewriter.VisitMethodCall(MethodCallExpression m)
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[TElement](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteDelete[TSource](IQueryable`1 source)
   at lambda_method34(Closure)
   at MockQueryable.Core.TestQueryProvider`1.CompileExpressionItem[TResult](Expression expression)
   at MockQueryable.Core.TestQueryProvider`1.Execute[TResult](Expression expression)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MockQueryable.EntityFrameworkCore.TestAsyncEnumerableEfCore`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteDeleteAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

Exception throws here on `.Invoke(this, new object[] { expression });`
https://github.com/romantitov/MockQueryable/blob/master/src/MockQueryable/MockQueryable.EntityFrameworkCore/TestQueryProviderEfCore.cs#L25

Same exception throws at ExecuteUpdateAsync (but it says ` There is no method 'ExecuteUpdate' on type 'Microsoft.EntityFrameworkCore.RelationalQueryableExtensions' that matches the specified arguments`)

The `custom logic` pattern doesn't work because ExecuteUpdateAsync / ExecuteDeleteAsync are IQueryable<T> extensions

Thank you very much

**Comment by StuartBale-Xero** [comment]
Is there a suggested approach on how to support this?
@SerhiyBalan - did you have a workaround?

**Comment by SerhiyBalan** [comment]
@StuartBale-Xero

My project uses UnitOfWork / GenericRepository pattern

So instead of using native EF's ExecuteUpdateAsync / ExecuteDeleteAsync extensions I use own methods at the Generic Repository:

```cs
public class GenericRepository<TEntity> : IRepository<TEntity>
    where TEntity : class, new()
{
    public GenericRepository(DbContext dbContext)
    {
        ArgumentNullException.ThrowIfNull(dbContext);
        DbSet = dbContext.Set<TEntity>();
    }

    protected DbSet<TEntity> DbSet { get; }

    ...

    public virtual Task<int> ExecuteUpdateAsync(
        Expression<Func<TEntity, bool>> predicate,
        Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> setPropertyCalls,
        CancellationToken cancellationToken = default)
        => DbSet
            .AsQueryable()
            .Where(predicate)
            .ExecuteUpdateAsync(setPropertyCalls, cancellationToken);

    public virtual Task<int> ExecuteDeleteAsync(
        Expression<Func<TEntity, bool>> predicate,
        CancellationToken cancellationToken = default)
        => DbSet
            .AsQueryable()
            .Where(predicate)
            .ExecuteDeleteAsync(cancellationToken);
}
```

In code instead of 
```cs
        await _unitOfWork
            .GetRepository<User>()
            .AsQueryable()
            .Where(user => user.Id == id)
            .ExecuteDeleteAsync();

```
I use my own methods:

```cs
        await _unitOfWork
            .GetRepository<User>()
            .ExecuteDeleteAsync(user => user.Id == id);
```

Since they are no more extensions, I can easily mock them

**Comment by marcoatribeiro** [comment]
Any update on this? I don't use the UoW / repository and that limitation is impacting my unit tests.

**Comment by tiagoseminotti** [comment]
> Hi, guys!
> 
> Any update on this? I don't use the UoW / repository and it would be really interesting if MockQueryable could support these methods.

same here...

**Comment by romantitov** [comment]
Hello. Thanks for you contribution. Sorry for the late answer. Unfortunately I'm very busy at the moment. If you provide a pull request with fix of the issue I would be happy to include it to the next release. Please don't forget to cover the case by additional tests to minimize possibility of regressions for the future. Thanks for the understanding.

**Comment by hpaygu-icims** [comment]
> @StuartBale-Xero
> 
> My project uses UnitOfWork / GenericRepository pattern
> 
> So instead of using native EF's ExecuteUpdateAsync / ExecuteDeleteAsync extensions I use own methods at the Generic Repository:
> 
> ```cs
> public class GenericRepository<TEntity> : IRepository<TEntity>
>     where TEntity : class, new()
> {
>     public GenericRepository(DbContext dbContext)
>     {
>         ArgumentNullException.ThrowIfNull(dbContext);
>         DbSet = dbContext.Set<TEntity>();
>     }
> 
>     protected DbSet<TEntity> DbSet { get; }
> 
>     ...
> 
>     public virtual Task<int> ExecuteUpdateAsync(
>         Expression<Func<TEntity, bool>> predicate,
>         Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> setPropertyCalls,
>         CancellationToken cancellationToken = default)
>         => DbSet
>             .AsQueryable()
>             .Where(predicate)
>             .ExecuteUpdateAsync(setPropertyCalls, cancellationToken);
> 
>     public virtual Task<int> ExecuteDeleteAsync(
>         Expression<Func<TEntity, bool>> predicate,
>         CancellationToken cancellationToken = default)
>         => DbSet
>             .AsQueryable()
>             .Where(predicate)
>             .ExecuteDeleteAsync(cancellationToken);
> }
> ```
> 
> In code instead of
> 
> ```cs
>         await _unitOfWork
>             .GetRepository<User>()
>             .AsQueryable()
>             .Where(user => user.Id == id)
>             .ExecuteDeleteAsync(); // Native Entity Framework extension
> ```
> 
> I use my own methods:
> 
> ```cs
>         await _unitOfWork
>             .GetRepository<User>()
>             .ExecuteDeleteAsync(user => user.Id == id); // My method in GenericRepository
> ```
> 
> Since they are no more extensions, I can easily mock them

But does it work well? since ExecuteUpdate doesn't follow UoW and repository pattern. My project has same scenario where existing code is using repository pattern and UoW since I need to implement bulk update action, I'm clueless how to do it if I already have repository pattern in place

**Comment by icnocop** [comment]
Thank you, Roman.

I recently made a comment to the PR [here](https://github.com/romantitov/MockQueryable/pull/81#issuecomment-2369869543) and want to know if my assumption of how the mocked `ExecuteUpdate` and `ExecuteUpdateAsync` methods are expected to work is correct.

I expected the underlying data to be updated.

For example, given a mocked `DbSet<User>`, which was created from a list containing one `User` with `Id` `1`, when `dbSet.Where(x => x.Id == 1).ExecuteUpdate(x => x.SetProperty(x => x.FirstName, "New first name"));` is called, then I expected the user's first name to be updated.

If that's the wrong assumption, is there a way to update the underlying data when `ExecuteUpdate` or `ExecuteUpdateAsync` is called such that the entities are updated according to the `SetProperty` method?

Thank you.

**Comment by mithun-shirali** [comment]
> Hello everyone. @lazaro-ansaldi made a great contribution for the issue in his pull request. Thanks @lazaro-ansaldi for that! The source code is currently available in a separate branch and in the release `7.0.4-beta`. Please feel free to give me your feedback. Once everyone will be happy I will merge these changes into the master branch and create a regular release.

Thanks @romantitov & @lazaro-ansaldi . This worked for me!

**Comment by pooyahadavi** [comment]
Big thanks to @romantitov and @lazaro-ansaldi. I also used the new feature for testing ExecuteUpdateAsync

**Comment by jeffmdemers** [comment]
I'm using 7.0.4-beta and testing using ExecuteDeleteAsync, and the problem persists. I receive the following error.

`Specified method is not supported.
   at Microsoft.EntityFrameworkCore.DbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)`

**Comment by romantitov** [comment]
Done in v8.0.0 - Thanks @Catlandor

**Comment by thedeany** [comment]
@Catlandor many thanks, and apologies for the oversight!
